AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: may-lmd-clients-gendoc-deleteS3   
Parameters:
  PositiveS3OutBucketName:
    Type: String
    Description: Nombre del bucket para los archivos resultado procesados positivo
    Default: ""  
  PolicyBoundary:
    Type: String
    Description: Valor del permission boundary para la creacion de roles
    Default: "" 
  VPCApiMayorista:
    Type: String
    Description: VPC ApiMayorista para conexion a internet
  subNet1:
    Type: String
    Description: SubNet ApiMayorista para conexion a internet
    Default: ""
  subNet2:
    Type: String
    Description: SubNet ApiMayorista para conexion a internet
    Default: ""
  securityVPC:
    Type: String
    Description: Grupo de seguridad de ApiMayorista para conexion a internet
  pKMSKeyID:
    Type: String
    Description: Llave kms para el manejo de encriptación.
  pKMSKeyDynamoID:
    Type: String
    Description: Llave kms para el manejo de encriptación con dynamo.
  routeTableId:
    Type: String
    Description: Id de la ruta de la tabla ApiMayorista para conexion a internet
    Default: ""
  DynamoTable:
    Type: String
    Description: Nombre de la tabla DynamoDB para Certificados Deceval Procesados
    Default: ""

Resources:
  LmdGendocDeletePj:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    #checkov:skip=CKV_AWS_116:No need for DLQ on this Lambda.    
    #checkov:skip=CKV_AWS_115:The concurrency is not defined yet.
    Properties:    
      FunctionName: may-lmd-clients-gendoc-deleteS3-pj
      CodeUri: src/
      Handler: index.lambdaHandler
      Runtime: nodejs20.x
      Role: !GetAtt MayLmdGendocDeletepjRole.Arn
      MemorySize: 512
      Timeout: 120
      EphemeralStorage:
        Size: 512 
      EventInvokeConfig:
        MaximumEventAgeInSeconds: 21600
        MaximumRetryAttempts: 2
      PackageType: Zip
      SnapStart:
        ApplyOn: None
      VpcConfig:
        SecurityGroupIds:
        - !Sub ${securityVPC}
        SubnetIds:
        - !Sub ${subNet1}
        - !Sub ${subNet2}
      RuntimeManagementConfig:
        UpdateRuntimeOn: Auto      
      Architectures:
        - x86_64

   # Rol de may-lmd-clients-gendoc-deleteS3-pj   
  MayLmdGendocDeletepjRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: may-lmd-clients-gendoc-deleteS3-pjRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:                
                - lambda.amazonaws.com
                - events.amazonaws.com
            Action: 'sts:AssumeRole'
      Description: "Rol que va a asumir la Lambda may-lmd-clients-gendoc-deleteS3-pj"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole 
        - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
      PermissionsBoundary: !Sub 'arn:aws:iam::${AWS::AccountId}:policy/${PolicyBoundary}'
      Path: '/dev/'
      Policies: 
        - PolicyName: S3GenDocTxtDelPDFPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: S3GenDelPermissions
                Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:DeleteObject
                Resource:
                  - !Sub 'arn:aws:s3:::${PositiveS3OutBucketName}/*'
              - Sid: S3ListGenDelPermissions
                Effect: Allow
                Action:
                  - s3:ListBucket
                # cfn-lint: disable=W1031
                Resource:
                  - !Sub 'arn:aws:s3:::${PositiveS3OutBucketName}'
              - Sid: KMSEncriptPermissions
                Effect: Allow
                Action:
                  - kms:Decrypt
                  - kms:Encrypt
                  - kms:GenerateDataKey
                Resource:
                  - !Ref pKMSKeyID
                  - !Ref pKMSKeyDynamoID
        - PolicyName: AccedeParamGenDelPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - ssm:GetParametersByPath
                  - ssm:GetParameters
                  - ssm:GetParameter
                Resource:
                  - !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/gen-delete/configuration/*'
        - PolicyName: DynamoGenDelDocPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: DynamoAccGenDelPerm
                Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem              
                  - dynamodb:Scan
                  - dynamodb:BatchWriteItem
                  - dynamodb:DescribeTable
                  - kms:Decrypt
                  - kms:Encrypt
                  - kms:GenerateDataKey                                   
                Resource:
                  - !Sub 'arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${DynamoTable}'           
  
   # Nueva política administrada para invocar la Lambda
  InvokeLmdManagedPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: pj-invoke-lmd-managed-policy
      Roles:
        - !Ref MayLmdGendocDeletepjRole
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action: lambda:InvokeFunction
            Resource:
              - !GetAtt LmdGendocDeletePj.Arn

  # Amazon EventBridge Rule (Scheduler)
  rSchedulerRuleRC:
    Type: AWS::Events::Rule    
    Properties:
      Name: ScheduleLambdaGetdocDelete
      ScheduleExpression: cron(30 15,20,22 ? * MON-FRI *)
      State: ENABLED
      Targets:
        - Id: Target1
          Arn: !GetAtt LmdGendocDeletePj.Arn
          RoleArn: !GetAtt MayLmdGendocDeletepjRole.Arn 
    
  pPositiveS3OutBucketName:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /gen-delete/configuration/aws.s3.bucket-salida-textract
      Type: String
      Value: !Sub ${PositiveS3OutBucketName}
      Description: Nombre del bucket S3 donde se carga archivo txt procesado resultado. 

  pTableRegDeceval:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /gen-delete/configuration/aws.dynamo.table-name-consolidated
      Type: String
      Value: !Sub ${DynamoTable}
      Description: Tabla de registro de Certificados procesados  

Outputs:
  LambdaFunctionArn:
    Description: "Lambda crea resultados en un formato txt y eliminacion de PDF y txt despues proceso"
    Value: !GetAtt MayLmdGendocDeletepjRole.Arn